# Generated by Django 5.1.1 on 2025-10-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderanswer',
            name='projected_preparation_time_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='preparationstep',
            name='delaytime_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
