# Generated by Django 5.1.1 on 2025-10-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='unit_price_cents',
            new_name='unit_price_NOK',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_cents',
        ),
        migrations.AddField(
            model_name='product',
            name='price_NOK',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
