# Generated by Django 5.1.1 on 2025-10-22 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0002_orderanswer_projected_preparation_time_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='has_been_picked_up',
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_delivery_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_pickup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
