services:
  backend:
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_DEBUG: 1
    volumes:
      - ./backend:/app

  frontend-dev:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm i && npm run dev -- --host"
    volumes:
      - ./frontend:/app
      - node_modules_cache:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "1"   # makes file watching reliable in Docker
      WATCHPACK_POLLING: "true"
    depends_on:
      - backend
      
volumes:
  node_modules_cache:
